baseURL: http://bram.vanmeurs.dev/
languageCode: en-us
title: bram.vanmeurs.dev
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Welcome to my website
        Content: A blog about tech, Python and MLOps
